### PR TITLE
Duplicate file and whitespace cleanup

### PR DESCRIPTION
**Pull request by turboencabulator**
Placing most of these type of changes into a single PR so as not to pollute other PRs.

### CODE REVIEW

**Comment by nrnrnr** [comment]
Do you mind telling me what problem is being solved here?

**Comment by turboencabulator** [comment]
This is another part of breaking up PR #10.  I've got other pieces on the way, but holding them back until this is in so I don't have merge conflicts.

**Comment by nrnrnr** [comment]
I reviewed the discussion on that PR, and I didn't find anything to support all these changes in whitespace.  I hate to say it, but they look gratuitous.  Why not simply drop this patch?

**Comment by turboencabulator** [comment]
I'm just trying to get some progress on the things I need from #10 since it's been sitting there for over 2 years now.  The point of this PR is to fix some consistency issues that will make future PRs smaller and simpler to review, since that seemed to be the roadblock on #10.

**Comment by nrnrnr** [comment]
Well, I'm skeptical, but you've put more effort into this than I have, and I don't see that the patch does real harm.  So I'll merge it.

**Pull request closed without merging**
